-- Setika platform master data for country/currency and timezone selectors.
-- Generated from IANA timezone identifiers exposed by Node/ICU and CLDR country/currency JSON metadata.
CREATE SCHEMA IF NOT EXISTS platform;

CREATE TABLE IF NOT EXISTS platform.timezones (
    id TEXT PRIMARY KEY,
    display_name TEXT NOT NULL,
    region TEXT NOT NULL,
    utc_offset_minutes INTEGER NOT NULL,
    utc_offset TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS platform.countries (
    iso_alpha2 CHAR(2) PRIMARY KEY,
    name TEXT NOT NULL,
    currency_code CHAR(3) NOT NULL,
    currency_name TEXT NOT NULL,
    currency_symbol TEXT NOT NULL,
    flag_emoji TEXT NOT NULL,
    default_timezone_id TEXT NULL REFERENCES platform.timezones(id),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_platform_timezones_active_region ON platform.timezones (is_active, region, display_name);
CREATE INDEX IF NOT EXISTS idx_platform_countries_active_name ON platform.countries (is_active, name);

INSERT INTO platform.timezones (id, display_name, region, utc_offset_minutes, utc_offset, is_active) VALUES
    ('Africa/Abidjan', 'Africa/Abidjan (UTC+00:00)', 'Africa', 0, 'UTC+00:00', TRUE),
    ('Africa/Accra', 'Africa/Accra (UTC+00:00)', 'Africa', 0, 'UTC+00:00', TRUE),
    ('Africa/Bamako', 'Africa/Bamako (UTC+00:00)', 'Africa', 0, 'UTC+00:00', TRUE),
    ('Africa/Banjul', 'Africa/Banjul (UTC+00:00)', 'Africa', 0, 'UTC+00:00', TRUE),
    ('Africa/Bissau', 'Africa/Bissau (UTC+00:00)', 'Africa', 0, 'UTC+00:00', TRUE),
    ('Africa/Conakry', 'Africa/Conakry (UTC+00:00)', 'Africa', 0, 'UTC+00:00', TRUE),
    ('Africa/Dakar', 'Africa/Dakar (UTC+00:00)', 'Africa', 0, 'UTC+00:00', TRUE),
    ('Africa/Freetown', 'Africa/Freetown (UTC+00:00)', 'Africa', 0, 'UTC+00:00', TRUE),
    ('Africa/Lome', 'Africa/Lome (UTC+00:00)', 'Africa', 0, 'UTC+00:00', TRUE),
    ('Africa/Monrovia', 'Africa/Monrovia (UTC+00:00)', 'Africa', 0, 'UTC+00:00', TRUE),
    ('Africa/Nouakchott', 'Africa/Nouakchott (UTC+00:00)', 'Africa', 0, 'UTC+00:00', TRUE),
    ('Africa/Ouagadougou', 'Africa/Ouagadougou (UTC+00:00)', 'Africa', 0, 'UTC+00:00', TRUE),
    ('Africa/Sao_Tome', 'Africa/Sao Tome (UTC+00:00)', 'Africa', 0, 'UTC+00:00', TRUE),
    ('Africa/Algiers', 'Africa/Algiers (UTC+01:00)', 'Africa', 60, 'UTC+01:00', TRUE),
    ('Africa/Bangui', 'Africa/Bangui (UTC+01:00)', 'Africa', 60, 'UTC+01:00', TRUE),
    ('Africa/Brazzaville', 'Africa/Brazzaville (UTC+01:00)', 'Africa', 60, 'UTC+01:00', TRUE),
    ('Africa/Casablanca', 'Africa/Casablanca (UTC+01:00)', 'Africa', 60, 'UTC+01:00', TRUE),
    ('Africa/Douala', 'Africa/Douala (UTC+01:00)', 'Africa', 60, 'UTC+01:00', TRUE),
    ('Africa/El_Aaiun', 'Africa/El Aaiun (UTC+01:00)', 'Africa', 60, 'UTC+01:00', TRUE),
    ('Africa/Kinshasa', 'Africa/Kinshasa (UTC+01:00)', 'Africa', 60, 'UTC+01:00', TRUE),
    ('Africa/Lagos', 'Africa/Lagos (UTC+01:00)', 'Africa', 60, 'UTC+01:00', TRUE),
    ('Africa/Libreville', 'Africa/Libreville (UTC+01:00)', 'Africa', 60, 'UTC+01:00', TRUE),
    ('Africa/Luanda', 'Africa/Luanda (UTC+01:00)', 'Africa', 60, 'UTC+01:00', TRUE),
    ('Africa/Malabo', 'Africa/Malabo (UTC+01:00)', 'Africa', 60, 'UTC+01:00', TRUE),
    ('Africa/Ndjamena', 'Africa/Ndjamena (UTC+01:00)', 'Africa', 60, 'UTC+01:00', TRUE),
    ('Africa/Niamey', 'Africa/Niamey (UTC+01:00)', 'Africa', 60, 'UTC+01:00', TRUE),
    ('Africa/Porto-Novo', 'Africa/Porto-Novo (UTC+01:00)', 'Africa', 60, 'UTC+01:00', TRUE),
    ('Africa/Tunis', 'Africa/Tunis (UTC+01:00)', 'Africa', 60, 'UTC+01:00', TRUE),
    ('Africa/Blantyre', 'Africa/Blantyre (UTC+02:00)', 'Africa', 120, 'UTC+02:00', TRUE),
    ('Africa/Bujumbura', 'Africa/Bujumbura (UTC+02:00)', 'Africa', 120, 'UTC+02:00', TRUE),
    ('Africa/Ceuta', 'Africa/Ceuta (UTC+02:00)', 'Africa', 120, 'UTC+02:00', TRUE),
    ('Africa/Gaborone', 'Africa/Gaborone (UTC+02:00)', 'Africa', 120, 'UTC+02:00', TRUE),
    ('Africa/Harare', 'Africa/Harare (UTC+02:00)', 'Africa', 120, 'UTC+02:00', TRUE),
    ('Africa/Johannesburg', 'Africa/Johannesburg (UTC+02:00)', 'Africa', 120, 'UTC+02:00', TRUE),
    ('Africa/Juba', 'Africa/Juba (UTC+02:00)', 'Africa', 120, 'UTC+02:00', TRUE),
    ('Africa/Khartoum', 'Africa/Khartoum (UTC+02:00)', 'Africa', 120, 'UTC+02:00', TRUE),
    ('Africa/Kigali', 'Africa/Kigali (UTC+02:00)', 'Africa', 120, 'UTC+02:00', TRUE),
    ('Africa/Lubumbashi', 'Africa/Lubumbashi (UTC+02:00)', 'Africa', 120, 'UTC+02:00', TRUE),
    ('Africa/Lusaka', 'Africa/Lusaka (UTC+02:00)', 'Africa', 120, 'UTC+02:00', TRUE),
    ('Africa/Maputo', 'Africa/Maputo (UTC+02:00)', 'Africa', 120, 'UTC+02:00', TRUE),
    ('Africa/Maseru', 'Africa/Maseru (UTC+02:00)', 'Africa', 120, 'UTC+02:00', TRUE),
    ('Africa/Mbabane', 'Africa/Mbabane (UTC+02:00)', 'Africa', 120, 'UTC+02:00', TRUE),
    ('Africa/Tripoli', 'Africa/Tripoli (UTC+02:00)', 'Africa', 120, 'UTC+02:00', TRUE),
    ('Africa/Windhoek', 'Africa/Windhoek (UTC+02:00)', 'Africa', 120, 'UTC+02:00', TRUE),
    ('Africa/Addis_Ababa', 'Africa/Addis Ababa (UTC+03:00)', 'Africa', 180, 'UTC+03:00', TRUE),
    ('Africa/Asmera', 'Africa/Asmera (UTC+03:00)', 'Africa', 180, 'UTC+03:00', TRUE),
    ('Africa/Cairo', 'Africa/Cairo (UTC+03:00)', 'Africa', 180, 'UTC+03:00', TRUE),
    ('Africa/Dar_es_Salaam', 'Africa/Dar es Salaam (UTC+03:00)', 'Africa', 180, 'UTC+03:00', TRUE),
    ('Africa/Djibouti', 'Africa/Djibouti (UTC+03:00)', 'Africa', 180, 'UTC+03:00', TRUE),
    ('Africa/Kampala', 'Africa/Kampala (UTC+03:00)', 'Africa', 180, 'UTC+03:00', TRUE),
    ('Africa/Mogadishu', 'Africa/Mogadishu (UTC+03:00)', 'Africa', 180, 'UTC+03:00', TRUE),
    ('Africa/Nairobi', 'Africa/Nairobi (UTC+03:00)', 'Africa', 180, 'UTC+03:00', TRUE),
    ('America/Adak', 'America/Adak (UTC-09:00)', 'America', -540, 'UTC-09:00', TRUE),
    ('America/Anchorage', 'America/Anchorage (UTC-08:00)', 'America', -480, 'UTC-08:00', TRUE),
    ('America/Juneau', 'America/Juneau (UTC-08:00)', 'America', -480, 'UTC-08:00', TRUE),
    ('America/Metlakatla', 'America/Metlakatla (UTC-08:00)', 'America', -480, 'UTC-08:00', TRUE),
    ('America/Nome', 'America/Nome (UTC-08:00)', 'America', -480, 'UTC-08:00', TRUE),
    ('America/Sitka', 'America/Sitka (UTC-08:00)', 'America', -480, 'UTC-08:00', TRUE),
    ('America/Yakutat', 'America/Yakutat (UTC-08:00)', 'America', -480, 'UTC-08:00', TRUE),
    ('America/Creston', 'America/Creston (UTC-07:00)', 'America', -420, 'UTC-07:00', TRUE),
    ('America/Dawson', 'America/Dawson (UTC-07:00)', 'America', -420, 'UTC-07:00', TRUE),
    ('America/Dawson_Creek', 'America/Dawson Creek (UTC-07:00)', 'America', -420, 'UTC-07:00', TRUE),
    ('America/Fort_Nelson', 'America/Fort Nelson (UTC-07:00)', 'America', -420, 'UTC-07:00', TRUE),
    ('America/Hermosillo', 'America/Hermosillo (UTC-07:00)', 'America', -420, 'UTC-07:00', TRUE),
    ('America/Los_Angeles', 'America/Los Angeles (UTC-07:00)', 'America', -420, 'UTC-07:00', TRUE),
    ('America/Mazatlan', 'America/Mazatlan (UTC-07:00)', 'America', -420, 'UTC-07:00', TRUE),
    ('America/Phoenix', 'America/Phoenix (UTC-07:00)', 'America', -420, 'UTC-07:00', TRUE),
    ('America/Tijuana', 'America/Tijuana (UTC-07:00)', 'America', -420, 'UTC-07:00', TRUE),
    ('America/Vancouver', 'America/Vancouver (UTC-07:00)', 'America', -420, 'UTC-07:00', TRUE),
    ('America/Whitehorse', 'America/Whitehorse (UTC-07:00)', 'America', -420, 'UTC-07:00', TRUE),
    ('America/Bahia_Banderas', 'America/Bahia Banderas (UTC-06:00)', 'America', -360, 'UTC-06:00', TRUE),
    ('America/Belize', 'America/Belize (UTC-06:00)', 'America', -360, 'UTC-06:00', TRUE),
    ('America/Boise', 'America/Boise (UTC-06:00)', 'America', -360, 'UTC-06:00', TRUE),
    ('America/Cambridge_Bay', 'America/Cambridge Bay (UTC-06:00)', 'America', -360, 'UTC-06:00', TRUE),
    ('America/Chihuahua', 'America/Chihuahua (UTC-06:00)', 'America', -360, 'UTC-06:00', TRUE),
    ('America/Ciudad_Juarez', 'America/Ciudad Juarez (UTC-06:00)', 'America', -360, 'UTC-06:00', TRUE),
    ('America/Costa_Rica', 'America/Costa Rica (UTC-06:00)', 'America', -360, 'UTC-06:00', TRUE),
    ('America/Denver', 'America/Denver (UTC-06:00)', 'America', -360, 'UTC-06:00', TRUE),
    ('America/Edmonton', 'America/Edmonton (UTC-06:00)', 'America', -360, 'UTC-06:00', TRUE),
    ('America/El_Salvador', 'America/El Salvador (UTC-06:00)', 'America', -360, 'UTC-06:00', TRUE),
    ('America/Guatemala', 'America/Guatemala (UTC-06:00)', 'America', -360, 'UTC-06:00', TRUE),
    ('America/Inuvik', 'America/Inuvik (UTC-06:00)', 'America', -360, 'UTC-06:00', TRUE),
    ('America/Managua', 'America/Managua (UTC-06:00)', 'America', -360, 'UTC-06:00', TRUE),
    ('America/Merida', 'America/Merida (UTC-06:00)', 'America', -360, 'UTC-06:00', TRUE),
    ('America/Mexico_City', 'America/Mexico City (UTC-06:00)', 'America', -360, 'UTC-06:00', TRUE),
    ('America/Monterrey', 'America/Monterrey (UTC-06:00)', 'America', -360, 'UTC-06:00', TRUE),
    ('America/Regina', 'America/Regina (UTC-06:00)', 'America', -360, 'UTC-06:00', TRUE),
    ('America/Swift_Current', 'America/Swift Current (UTC-06:00)', 'America', -360, 'UTC-06:00', TRUE),
    ('America/Tegucigalpa', 'America/Tegucigalpa (UTC-06:00)', 'America', -360, 'UTC-06:00', TRUE),
    ('America/Bogota', 'America/Bogota (UTC-05:00)', 'America', -300, 'UTC-05:00', TRUE),
    ('America/Cancun', 'America/Cancun (UTC-05:00)', 'America', -300, 'UTC-05:00', TRUE),
    ('America/Cayman', 'America/Cayman (UTC-05:00)', 'America', -300, 'UTC-05:00', TRUE),
    ('America/Chicago', 'America/Chicago (UTC-05:00)', 'America', -300, 'UTC-05:00', TRUE),
    ('America/Coral_Harbour', 'America/Coral Harbour (UTC-05:00)', 'America', -300, 'UTC-05:00', TRUE),
    ('America/Eirunepe', 'America/Eirunepe (UTC-05:00)', 'America', -300, 'UTC-05:00', TRUE),
    ('America/Guayaquil', 'America/Guayaquil (UTC-05:00)', 'America', -300, 'UTC-05:00', TRUE),
    ('America/Indiana/Knox', 'America/Indiana/Knox (UTC-05:00)', 'America', -300, 'UTC-05:00', TRUE),
    ('America/Indiana/Tell_City', 'America/Indiana/Tell City (UTC-05:00)', 'America', -300, 'UTC-05:00', TRUE),
    ('America/Jamaica', 'America/Jamaica (UTC-05:00)', 'America', -300, 'UTC-05:00', TRUE),
    ('America/Lima', 'America/Lima (UTC-05:00)', 'America', -300, 'UTC-05:00', TRUE),
    ('America/Matamoros', 'America/Matamoros (UTC-05:00)', 'America', -300, 'UTC-05:00', TRUE),
    ('America/Menominee', 'America/Menominee (UTC-05:00)', 'America', -300, 'UTC-05:00', TRUE),
    ('America/North_Dakota/Beulah', 'America/North Dakota/Beulah (UTC-05:00)', 'America', -300, 'UTC-05:00', TRUE),
    ('America/North_Dakota/Center', 'America/North Dakota/Center (UTC-05:00)', 'America', -300, 'UTC-05:00', TRUE),
    ('America/North_Dakota/New_Salem', 'America/North Dakota/New Salem (UTC-05:00)', 'America', -300, 'UTC-05:00', TRUE),
    ('America/Ojinaga', 'America/Ojinaga (UTC-05:00)', 'America', -300, 'UTC-05:00', TRUE),
    ('America/Panama', 'America/Panama (UTC-05:00)', 'America', -300, 'UTC-05:00', TRUE),
    ('America/Rankin_Inlet', 'America/Rankin Inlet (UTC-05:00)', 'America', -300, 'UTC-05:00', TRUE),
    ('America/Resolute', 'America/Resolute (UTC-05:00)', 'America', -300, 'UTC-05:00', TRUE),
    ('America/Rio_Branco', 'America/Rio Branco (UTC-05:00)', 'America', -300, 'UTC-05:00', TRUE),
    ('America/Winnipeg', 'America/Winnipeg (UTC-05:00)', 'America', -300, 'UTC-05:00', TRUE),
    ('America/Anguilla', 'America/Anguilla (UTC-04:00)', 'America', -240, 'UTC-04:00', TRUE),
    ('America/Antigua', 'America/Antigua (UTC-04:00)', 'America', -240, 'UTC-04:00', TRUE),
    ('America/Aruba', 'America/Aruba (UTC-04:00)', 'America', -240, 'UTC-04:00', TRUE),
    ('America/Barbados', 'America/Barbados (UTC-04:00)', 'America', -240, 'UTC-04:00', TRUE),
    ('America/Blanc-Sablon', 'America/Blanc-Sablon (UTC-04:00)', 'America', -240, 'UTC-04:00', TRUE),
    ('America/Boa_Vista', 'America/Boa Vista (UTC-04:00)', 'America', -240, 'UTC-04:00', TRUE),
    ('America/Campo_Grande', 'America/Campo Grande (UTC-04:00)', 'America', -240, 'UTC-04:00', TRUE),
    ('America/Caracas', 'America/Caracas (UTC-04:00)', 'America', -240, 'UTC-04:00', TRUE),
    ('America/Cuiaba', 'America/Cuiaba (UTC-04:00)', 'America', -240, 'UTC-04:00', TRUE),
    ('America/Curacao', 'America/Curacao (UTC-04:00)', 'America', -240, 'UTC-04:00', TRUE),
    ('America/Detroit', 'America/Detroit (UTC-04:00)', 'America', -240, 'UTC-04:00', TRUE),
    ('America/Dominica', 'America/Dominica (UTC-04:00)', 'America', -240, 'UTC-04:00', TRUE),
    ('America/Grand_Turk', 'America/Grand Turk (UTC-04:00)', 'America', -240, 'UTC-04:00', TRUE),
    ('America/Grenada', 'America/Grenada (UTC-04:00)', 'America', -240, 'UTC-04:00', TRUE),
    ('America/Guadeloupe', 'America/Guadeloupe (UTC-04:00)', 'America', -240, 'UTC-04:00', TRUE),
    ('America/Guyana', 'America/Guyana (UTC-04:00)', 'America', -240, 'UTC-04:00', TRUE),
    ('America/Havana', 'America/Havana (UTC-04:00)', 'America', -240, 'UTC-04:00', TRUE),
    ('America/Indiana/Marengo', 'America/Indiana/Marengo (UTC-04:00)', 'America', -240, 'UTC-04:00', TRUE),
    ('America/Indiana/Petersburg', 'America/Indiana/Petersburg (UTC-04:00)', 'America', -240, 'UTC-04:00', TRUE),
    ('America/Indiana/Vevay', 'America/Indiana/Vevay (UTC-04:00)', 'America', -240, 'UTC-04:00', TRUE),
    ('America/Indiana/Vincennes', 'America/Indiana/Vincennes (UTC-04:00)', 'America', -240, 'UTC-04:00', TRUE),
    ('America/Indiana/Winamac', 'America/Indiana/Winamac (UTC-04:00)', 'America', -240, 'UTC-04:00', TRUE),
    ('America/Indianapolis', 'America/Indianapolis (UTC-04:00)', 'America', -240, 'UTC-04:00', TRUE),
    ('America/Iqaluit', 'America/Iqaluit (UTC-04:00)', 'America', -240, 'UTC-04:00', TRUE),
    ('America/Kentucky/Monticello', 'America/Kentucky/Monticello (UTC-04:00)', 'America', -240, 'UTC-04:00', TRUE),
    ('America/Kralendijk', 'America/Kralendijk (UTC-04:00)', 'America', -240, 'UTC-04:00', TRUE),
    ('America/La_Paz', 'America/La Paz (UTC-04:00)', 'America', -240, 'UTC-04:00', TRUE),
    ('America/Louisville', 'America/Louisville (UTC-04:00)', 'America', -240, 'UTC-04:00', TRUE),
    ('America/Lower_Princes', 'America/Lower Princes (UTC-04:00)', 'America', -240, 'UTC-04:00', TRUE),
    ('America/Manaus', 'America/Manaus (UTC-04:00)', 'America', -240, 'UTC-04:00', TRUE),
    ('America/Marigot', 'America/Marigot (UTC-04:00)', 'America', -240, 'UTC-04:00', TRUE),
    ('America/Martinique', 'America/Martinique (UTC-04:00)', 'America', -240, 'UTC-04:00', TRUE),
    ('America/Montserrat', 'America/Montserrat (UTC-04:00)', 'America', -240, 'UTC-04:00', TRUE),
    ('America/Nassau', 'America/Nassau (UTC-04:00)', 'America', -240, 'UTC-04:00', TRUE),
    ('America/New_York', 'America/New York (UTC-04:00)', 'America', -240, 'UTC-04:00', TRUE),
    ('America/Port_of_Spain', 'America/Port of Spain (UTC-04:00)', 'America', -240, 'UTC-04:00', TRUE),
    ('America/Port-au-Prince', 'America/Port-au-Prince (UTC-04:00)', 'America', -240, 'UTC-04:00', TRUE),
    ('America/Porto_Velho', 'America/Porto Velho (UTC-04:00)', 'America', -240, 'UTC-04:00', TRUE),
    ('America/Puerto_Rico', 'America/Puerto Rico (UTC-04:00)', 'America', -240, 'UTC-04:00', TRUE),
    ('America/Santiago', 'America/Santiago (UTC-04:00)', 'America', -240, 'UTC-04:00', TRUE),
    ('America/Santo_Domingo', 'America/Santo Domingo (UTC-04:00)', 'America', -240, 'UTC-04:00', TRUE),
    ('America/St_Barthelemy', 'America/St Barthelemy (UTC-04:00)', 'America', -240, 'UTC-04:00', TRUE),
    ('America/St_Kitts', 'America/St Kitts (UTC-04:00)', 'America', -240, 'UTC-04:00', TRUE),
    ('America/St_Lucia', 'America/St Lucia (UTC-04:00)', 'America', -240, 'UTC-04:00', TRUE),
    ('America/St_Thomas', 'America/St Thomas (UTC-04:00)', 'America', -240, 'UTC-04:00', TRUE),
    ('America/St_Vincent', 'America/St Vincent (UTC-04:00)', 'America', -240, 'UTC-04:00', TRUE),
    ('America/Toronto', 'America/Toronto (UTC-04:00)', 'America', -240, 'UTC-04:00', TRUE),
    ('America/Tortola', 'America/Tortola (UTC-04:00)', 'America', -240, 'UTC-04:00', TRUE),
    ('America/Araguaina', 'America/Araguaina (UTC-03:00)', 'America', -180, 'UTC-03:00', TRUE),
    ('America/Argentina/La_Rioja', 'America/Argentina/La Rioja (UTC-03:00)', 'America', -180, 'UTC-03:00', TRUE),
    ('America/Argentina/Rio_Gallegos', 'America/Argentina/Rio Gallegos (UTC-03:00)', 'America', -180, 'UTC-03:00', TRUE),
    ('America/Argentina/Salta', 'America/Argentina/Salta (UTC-03:00)', 'America', -180, 'UTC-03:00', TRUE),
    ('America/Argentina/San_Juan', 'America/Argentina/San Juan (UTC-03:00)', 'America', -180, 'UTC-03:00', TRUE),
    ('America/Argentina/San_Luis', 'America/Argentina/San Luis (UTC-03:00)', 'America', -180, 'UTC-03:00', TRUE),
    ('America/Argentina/Tucuman', 'America/Argentina/Tucuman (UTC-03:00)', 'America', -180, 'UTC-03:00', TRUE),
    ('America/Argentina/Ushuaia', 'America/Argentina/Ushuaia (UTC-03:00)', 'America', -180, 'UTC-03:00', TRUE),
    ('America/Asuncion', 'America/Asuncion (UTC-03:00)', 'America', -180, 'UTC-03:00', TRUE),
    ('America/Bahia', 'America/Bahia (UTC-03:00)', 'America', -180, 'UTC-03:00', TRUE),
    ('America/Belem', 'America/Belem (UTC-03:00)', 'America', -180, 'UTC-03:00', TRUE),
    ('America/Buenos_Aires', 'America/Buenos Aires (UTC-03:00)', 'America', -180, 'UTC-03:00', TRUE),
    ('America/Catamarca', 'America/Catamarca (UTC-03:00)', 'America', -180, 'UTC-03:00', TRUE),
    ('America/Cayenne', 'America/Cayenne (UTC-03:00)', 'America', -180, 'UTC-03:00', TRUE),
    ('America/Cordoba', 'America/Cordoba (UTC-03:00)', 'America', -180, 'UTC-03:00', TRUE),
    ('America/Coyhaique', 'America/Coyhaique (UTC-03:00)', 'America', -180, 'UTC-03:00', TRUE),
    ('America/Fortaleza', 'America/Fortaleza (UTC-03:00)', 'America', -180, 'UTC-03:00', TRUE),
    ('America/Glace_Bay', 'America/Glace Bay (UTC-03:00)', 'America', -180, 'UTC-03:00', TRUE),
    ('America/Goose_Bay', 'America/Goose Bay (UTC-03:00)', 'America', -180, 'UTC-03:00', TRUE),
    ('America/Halifax', 'America/Halifax (UTC-03:00)', 'America', -180, 'UTC-03:00', TRUE),
    ('America/Jujuy', 'America/Jujuy (UTC-03:00)', 'America', -180, 'UTC-03:00', TRUE),
    ('America/Maceio', 'America/Maceio (UTC-03:00)', 'America', -180, 'UTC-03:00', TRUE),
    ('America/Mendoza', 'America/Mendoza (UTC-03:00)', 'America', -180, 'UTC-03:00', TRUE),
    ('America/Moncton', 'America/Moncton (UTC-03:00)', 'America', -180, 'UTC-03:00', TRUE),
    ('America/Montevideo', 'America/Montevideo (UTC-03:00)', 'America', -180, 'UTC-03:00', TRUE),
    ('America/Paramaribo', 'America/Paramaribo (UTC-03:00)', 'America', -180, 'UTC-03:00', TRUE),
    ('America/Punta_Arenas', 'America/Punta Arenas (UTC-03:00)', 'America', -180, 'UTC-03:00', TRUE),
    ('America/Recife', 'America/Recife (UTC-03:00)', 'America', -180, 'UTC-03:00', TRUE),
    ('America/Santarem', 'America/Santarem (UTC-03:00)', 'America', -180, 'UTC-03:00', TRUE),
    ('America/Sao_Paulo', 'America/Sao Paulo (UTC-03:00)', 'America', -180, 'UTC-03:00', TRUE),
    ('America/Thule', 'America/Thule (UTC-03:00)', 'America', -180, 'UTC-03:00', TRUE),
    ('America/St_Johns', 'America/St Johns (UTC-02:30)', 'America', -150, 'UTC-02:30', TRUE),
    ('America/Miquelon', 'America/Miquelon (UTC-02:00)', 'America', -120, 'UTC-02:00', TRUE),
    ('America/Noronha', 'America/Noronha (UTC-02:00)', 'America', -120, 'UTC-02:00', TRUE),
    ('America/Godthab', 'America/Godthab (UTC-01:00)', 'America', -60, 'UTC-01:00', TRUE),
    ('America/Scoresbysund', 'America/Scoresbysund (UTC-01:00)', 'America', -60, 'UTC-01:00', TRUE),
    ('America/Danmarkshavn', 'America/Danmarkshavn (UTC+00:00)', 'America', 0, 'UTC+00:00', TRUE),
    ('Antarctica/Palmer', 'Antarctica/Palmer (UTC-03:00)', 'Antarctica', -180, 'UTC-03:00', TRUE),
    ('Antarctica/Rothera', 'Antarctica/Rothera (UTC-03:00)', 'Antarctica', -180, 'UTC-03:00', TRUE),
    ('Antarctica/Troll', 'Antarctica/Troll (UTC+02:00)', 'Antarctica', 120, 'UTC+02:00', TRUE),
    ('Antarctica/Syowa', 'Antarctica/Syowa (UTC+03:00)', 'Antarctica', 180, 'UTC+03:00', TRUE),
    ('Antarctica/Mawson', 'Antarctica/Mawson (UTC+05:00)', 'Antarctica', 300, 'UTC+05:00', TRUE),
    ('Antarctica/Vostok', 'Antarctica/Vostok (UTC+05:00)', 'Antarctica', 300, 'UTC+05:00', TRUE),
    ('Antarctica/Davis', 'Antarctica/Davis (UTC+07:00)', 'Antarctica', 420, 'UTC+07:00', TRUE),
    ('Antarctica/Casey', 'Antarctica/Casey (UTC+08:00)', 'Antarctica', 480, 'UTC+08:00', TRUE),
    ('Antarctica/DumontDUrville', 'Antarctica/DumontDUrville (UTC+10:00)', 'Antarctica', 600, 'UTC+10:00', TRUE),
    ('Antarctica/Macquarie', 'Antarctica/Macquarie (UTC+10:00)', 'Antarctica', 600, 'UTC+10:00', TRUE),
    ('Antarctica/McMurdo', 'Antarctica/McMurdo (UTC+12:00)', 'Antarctica', 720, 'UTC+12:00', TRUE),
    ('Arctic/Longyearbyen', 'Arctic/Longyearbyen (UTC+02:00)', 'Arctic', 120, 'UTC+02:00', TRUE),
    ('Asia/Aden', 'Asia/Aden (UTC+03:00)', 'Asia', 180, 'UTC+03:00', TRUE),
    ('Asia/Amman', 'Asia/Amman (UTC+03:00)', 'Asia', 180, 'UTC+03:00', TRUE),
    ('Asia/Baghdad', 'Asia/Baghdad (UTC+03:00)', 'Asia', 180, 'UTC+03:00', TRUE),
    ('Asia/Bahrain', 'Asia/Bahrain (UTC+03:00)', 'Asia', 180, 'UTC+03:00', TRUE),
    ('Asia/Beirut', 'Asia/Beirut (UTC+03:00)', 'Asia', 180, 'UTC+03:00', TRUE),
    ('Asia/Damascus', 'Asia/Damascus (UTC+03:00)', 'Asia', 180, 'UTC+03:00', TRUE),
    ('Asia/Famagusta', 'Asia/Famagusta (UTC+03:00)', 'Asia', 180, 'UTC+03:00', TRUE),
    ('Asia/Gaza', 'Asia/Gaza (UTC+03:00)', 'Asia', 180, 'UTC+03:00', TRUE),
    ('Asia/Hebron', 'Asia/Hebron (UTC+03:00)', 'Asia', 180, 'UTC+03:00', TRUE),
    ('Asia/Jerusalem', 'Asia/Jerusalem (UTC+03:00)', 'Asia', 180, 'UTC+03:00', TRUE),
    ('Asia/Kuwait', 'Asia/Kuwait (UTC+03:00)', 'Asia', 180, 'UTC+03:00', TRUE),
    ('Asia/Nicosia', 'Asia/Nicosia (UTC+03:00)', 'Asia', 180, 'UTC+03:00', TRUE),
    ('Asia/Qatar', 'Asia/Qatar (UTC+03:00)', 'Asia', 180, 'UTC+03:00', TRUE),
    ('Asia/Riyadh', 'Asia/Riyadh (UTC+03:00)', 'Asia', 180, 'UTC+03:00', TRUE),
    ('Asia/Tehran', 'Asia/Tehran (UTC+03:30)', 'Asia', 210, 'UTC+03:30', TRUE),
    ('Asia/Baku', 'Asia/Baku (UTC+04:00)', 'Asia', 240, 'UTC+04:00', TRUE),
    ('Asia/Dubai', 'Asia/Dubai (UTC+04:00)', 'Asia', 240, 'UTC+04:00', TRUE),
    ('Asia/Muscat', 'Asia/Muscat (UTC+04:00)', 'Asia', 240, 'UTC+04:00', TRUE),
    ('Asia/Tbilisi', 'Asia/Tbilisi (UTC+04:00)', 'Asia', 240, 'UTC+04:00', TRUE),
    ('Asia/Yerevan', 'Asia/Yerevan (UTC+04:00)', 'Asia', 240, 'UTC+04:00', TRUE),
    ('Asia/Kabul', 'Asia/Kabul (UTC+04:30)', 'Asia', 270, 'UTC+04:30', TRUE),
    ('Asia/Almaty', 'Asia/Almaty (UTC+05:00)', 'Asia', 300, 'UTC+05:00', TRUE),
    ('Asia/Aqtau', 'Asia/Aqtau (UTC+05:00)', 'Asia', 300, 'UTC+05:00', TRUE),
    ('Asia/Aqtobe', 'Asia/Aqtobe (UTC+05:00)', 'Asia', 300, 'UTC+05:00', TRUE),
    ('Asia/Ashgabat', 'Asia/Ashgabat (UTC+05:00)', 'Asia', 300, 'UTC+05:00', TRUE),
    ('Asia/Atyrau', 'Asia/Atyrau (UTC+05:00)', 'Asia', 300, 'UTC+05:00', TRUE),
    ('Asia/Dushanbe', 'Asia/Dushanbe (UTC+05:00)', 'Asia', 300, 'UTC+05:00', TRUE),
    ('Asia/Karachi', 'Asia/Karachi (UTC+05:00)', 'Asia', 300, 'UTC+05:00', TRUE),
    ('Asia/Oral', 'Asia/Oral (UTC+05:00)', 'Asia', 300, 'UTC+05:00', TRUE),
    ('Asia/Qostanay', 'Asia/Qostanay (UTC+05:00)', 'Asia', 300, 'UTC+05:00', TRUE),
    ('Asia/Qyzylorda', 'Asia/Qyzylorda (UTC+05:00)', 'Asia', 300, 'UTC+05:00', TRUE),
    ('Asia/Samarkand', 'Asia/Samarkand (UTC+05:00)', 'Asia', 300, 'UTC+05:00', TRUE),
    ('Asia/Tashkent', 'Asia/Tashkent (UTC+05:00)', 'Asia', 300, 'UTC+05:00', TRUE),
    ('Asia/Yekaterinburg', 'Asia/Yekaterinburg (UTC+05:00)', 'Asia', 300, 'UTC+05:00', TRUE),
    ('Asia/Calcutta', 'Asia/Calcutta (UTC+05:30)', 'Asia', 330, 'UTC+05:30', TRUE),
    ('Asia/Kolkata', 'Asia/Kolkata (UTC+05:30)', 'Asia', 330, 'UTC+05:30', TRUE),
    ('Asia/Colombo', 'Asia/Colombo (UTC+05:30)', 'Asia', 330, 'UTC+05:30', TRUE),
    ('Asia/Katmandu', 'Asia/Katmandu (UTC+05:45)', 'Asia', 345, 'UTC+05:45', TRUE),
    ('Asia/Bishkek', 'Asia/Bishkek (UTC+06:00)', 'Asia', 360, 'UTC+06:00', TRUE),
    ('Asia/Dhaka', 'Asia/Dhaka (UTC+06:00)', 'Asia', 360, 'UTC+06:00', TRUE),
    ('Asia/Omsk', 'Asia/Omsk (UTC+06:00)', 'Asia', 360, 'UTC+06:00', TRUE),
    ('Asia/Thimphu', 'Asia/Thimphu (UTC+06:00)', 'Asia', 360, 'UTC+06:00', TRUE),
    ('Asia/Urumqi', 'Asia/Urumqi (UTC+06:00)', 'Asia', 360, 'UTC+06:00', TRUE),
    ('Asia/Rangoon', 'Asia/Rangoon (UTC+06:30)', 'Asia', 390, 'UTC+06:30', TRUE),
    ('Asia/Bangkok', 'Asia/Bangkok (UTC+07:00)', 'Asia', 420, 'UTC+07:00', TRUE),
    ('Asia/Barnaul', 'Asia/Barnaul (UTC+07:00)', 'Asia', 420, 'UTC+07:00', TRUE),
    ('Asia/Hovd', 'Asia/Hovd (UTC+07:00)', 'Asia', 420, 'UTC+07:00', TRUE),
    ('Asia/Jakarta', 'Asia/Jakarta (UTC+07:00)', 'Asia', 420, 'UTC+07:00', TRUE),
    ('Asia/Krasnoyarsk', 'Asia/Krasnoyarsk (UTC+07:00)', 'Asia', 420, 'UTC+07:00', TRUE),
    ('Asia/Novokuznetsk', 'Asia/Novokuznetsk (UTC+07:00)', 'Asia', 420, 'UTC+07:00', TRUE),
    ('Asia/Novosibirsk', 'Asia/Novosibirsk (UTC+07:00)', 'Asia', 420, 'UTC+07:00', TRUE),
    ('Asia/Phnom_Penh', 'Asia/Phnom Penh (UTC+07:00)', 'Asia', 420, 'UTC+07:00', TRUE),
    ('Asia/Pontianak', 'Asia/Pontianak (UTC+07:00)', 'Asia', 420, 'UTC+07:00', TRUE),
    ('Asia/Saigon', 'Asia/Saigon (UTC+07:00)', 'Asia', 420, 'UTC+07:00', TRUE),
    ('Asia/Tomsk', 'Asia/Tomsk (UTC+07:00)', 'Asia', 420, 'UTC+07:00', TRUE),
    ('Asia/Vientiane', 'Asia/Vientiane (UTC+07:00)', 'Asia', 420, 'UTC+07:00', TRUE),
    ('Asia/Brunei', 'Asia/Brunei (UTC+08:00)', 'Asia', 480, 'UTC+08:00', TRUE),
    ('Asia/Hong_Kong', 'Asia/Hong Kong (UTC+08:00)', 'Asia', 480, 'UTC+08:00', TRUE),
    ('Asia/Irkutsk', 'Asia/Irkutsk (UTC+08:00)', 'Asia', 480, 'UTC+08:00', TRUE),
    ('Asia/Kuala_Lumpur', 'Asia/Kuala Lumpur (UTC+08:00)', 'Asia', 480, 'UTC+08:00', TRUE),
    ('Asia/Kuching', 'Asia/Kuching (UTC+08:00)', 'Asia', 480, 'UTC+08:00', TRUE),
    ('Asia/Macau', 'Asia/Macau (UTC+08:00)', 'Asia', 480, 'UTC+08:00', TRUE),
    ('Asia/Makassar', 'Asia/Makassar (UTC+08:00)', 'Asia', 480, 'UTC+08:00', TRUE),
    ('Asia/Manila', 'Asia/Manila (UTC+08:00)', 'Asia', 480, 'UTC+08:00', TRUE),
    ('Asia/Shanghai', 'Asia/Shanghai (UTC+08:00)', 'Asia', 480, 'UTC+08:00', TRUE),
    ('Asia/Singapore', 'Asia/Singapore (UTC+08:00)', 'Asia', 480, 'UTC+08:00', TRUE),
    ('Asia/Taipei', 'Asia/Taipei (UTC+08:00)', 'Asia', 480, 'UTC+08:00', TRUE),
    ('Asia/Ulaanbaatar', 'Asia/Ulaanbaatar (UTC+08:00)', 'Asia', 480, 'UTC+08:00', TRUE),
    ('Asia/Chita', 'Asia/Chita (UTC+09:00)', 'Asia', 540, 'UTC+09:00', TRUE),
    ('Asia/Dili', 'Asia/Dili (UTC+09:00)', 'Asia', 540, 'UTC+09:00', TRUE),
    ('Asia/Jayapura', 'Asia/Jayapura (UTC+09:00)', 'Asia', 540, 'UTC+09:00', TRUE),
    ('Asia/Khandyga', 'Asia/Khandyga (UTC+09:00)', 'Asia', 540, 'UTC+09:00', TRUE),
    ('Asia/Pyongyang', 'Asia/Pyongyang (UTC+09:00)', 'Asia', 540, 'UTC+09:00', TRUE),
    ('Asia/Seoul', 'Asia/Seoul (UTC+09:00)', 'Asia', 540, 'UTC+09:00', TRUE),
    ('Asia/Tokyo', 'Asia/Tokyo (UTC+09:00)', 'Asia', 540, 'UTC+09:00', TRUE),
    ('Asia/Yakutsk', 'Asia/Yakutsk (UTC+09:00)', 'Asia', 540, 'UTC+09:00', TRUE),
    ('Asia/Ust-Nera', 'Asia/Ust-Nera (UTC+10:00)', 'Asia', 600, 'UTC+10:00', TRUE),
    ('Asia/Vladivostok', 'Asia/Vladivostok (UTC+10:00)', 'Asia', 600, 'UTC+10:00', TRUE),
    ('Asia/Magadan', 'Asia/Magadan (UTC+11:00)', 'Asia', 660, 'UTC+11:00', TRUE),
    ('Asia/Sakhalin', 'Asia/Sakhalin (UTC+11:00)', 'Asia', 660, 'UTC+11:00', TRUE),
    ('Asia/Srednekolymsk', 'Asia/Srednekolymsk (UTC+11:00)', 'Asia', 660, 'UTC+11:00', TRUE),
    ('Asia/Anadyr', 'Asia/Anadyr (UTC+12:00)', 'Asia', 720, 'UTC+12:00', TRUE),
    ('Asia/Kamchatka', 'Asia/Kamchatka (UTC+12:00)', 'Asia', 720, 'UTC+12:00', TRUE),
    ('Atlantic/Bermuda', 'Atlantic/Bermuda (UTC-03:00)', 'Atlantic', -180, 'UTC-03:00', TRUE),
    ('Atlantic/Stanley', 'Atlantic/Stanley (UTC-03:00)', 'Atlantic', -180, 'UTC-03:00', TRUE),
    ('Atlantic/South_Georgia', 'Atlantic/South Georgia (UTC-02:00)', 'Atlantic', -120, 'UTC-02:00', TRUE),
    ('Atlantic/Cape_Verde', 'Atlantic/Cape Verde (UTC-01:00)', 'Atlantic', -60, 'UTC-01:00', TRUE),
    ('Atlantic/Azores', 'Atlantic/Azores (UTC+00:00)', 'Atlantic', 0, 'UTC+00:00', TRUE),
    ('Atlantic/Reykjavik', 'Atlantic/Reykjavik (UTC+00:00)', 'Atlantic', 0, 'UTC+00:00', TRUE),
    ('Atlantic/St_Helena', 'Atlantic/St Helena (UTC+00:00)', 'Atlantic', 0, 'UTC+00:00', TRUE),
    ('Atlantic/Canary', 'Atlantic/Canary (UTC+01:00)', 'Atlantic', 60, 'UTC+01:00', TRUE),
    ('Atlantic/Faeroe', 'Atlantic/Faeroe (UTC+01:00)', 'Atlantic', 60, 'UTC+01:00', TRUE),
    ('Atlantic/Madeira', 'Atlantic/Madeira (UTC+01:00)', 'Atlantic', 60, 'UTC+01:00', TRUE),
    ('Australia/Perth', 'Australia/Perth (UTC+08:00)', 'Australia', 480, 'UTC+08:00', TRUE),
    ('Australia/Eucla', 'Australia/Eucla (UTC+08:45)', 'Australia', 525, 'UTC+08:45', TRUE),
    ('Australia/Adelaide', 'Australia/Adelaide (UTC+09:30)', 'Australia', 570, 'UTC+09:30', TRUE),
    ('Australia/Broken_Hill', 'Australia/Broken Hill (UTC+09:30)', 'Australia', 570, 'UTC+09:30', TRUE),
    ('Australia/Darwin', 'Australia/Darwin (UTC+09:30)', 'Australia', 570, 'UTC+09:30', TRUE),
    ('Australia/Brisbane', 'Australia/Brisbane (UTC+10:00)', 'Australia', 600, 'UTC+10:00', TRUE),
    ('Australia/Hobart', 'Australia/Hobart (UTC+10:00)', 'Australia', 600, 'UTC+10:00', TRUE),
    ('Australia/Lindeman', 'Australia/Lindeman (UTC+10:00)', 'Australia', 600, 'UTC+10:00', TRUE),
    ('Australia/Melbourne', 'Australia/Melbourne (UTC+10:00)', 'Australia', 600, 'UTC+10:00', TRUE),
    ('Australia/Sydney', 'Australia/Sydney (UTC+10:00)', 'Australia', 600, 'UTC+10:00', TRUE),
    ('Australia/Lord_Howe', 'Australia/Lord Howe (UTC+10:30)', 'Australia', 630, 'UTC+10:30', TRUE),
    ('Europe/Dublin', 'Europe/Dublin (UTC+01:00)', 'Europe', 60, 'UTC+01:00', TRUE),
    ('Europe/Guernsey', 'Europe/Guernsey (UTC+01:00)', 'Europe', 60, 'UTC+01:00', TRUE),
    ('Europe/Isle_of_Man', 'Europe/Isle of Man (UTC+01:00)', 'Europe', 60, 'UTC+01:00', TRUE),
    ('Europe/Jersey', 'Europe/Jersey (UTC+01:00)', 'Europe', 60, 'UTC+01:00', TRUE),
    ('Europe/Lisbon', 'Europe/Lisbon (UTC+01:00)', 'Europe', 60, 'UTC+01:00', TRUE),
    ('Europe/London', 'Europe/London (UTC+01:00)', 'Europe', 60, 'UTC+01:00', TRUE),
    ('Europe/Amsterdam', 'Europe/Amsterdam (UTC+02:00)', 'Europe', 120, 'UTC+02:00', TRUE),
    ('Europe/Andorra', 'Europe/Andorra (UTC+02:00)', 'Europe', 120, 'UTC+02:00', TRUE),
    ('Europe/Belgrade', 'Europe/Belgrade (UTC+02:00)', 'Europe', 120, 'UTC+02:00', TRUE),
    ('Europe/Berlin', 'Europe/Berlin (UTC+02:00)', 'Europe', 120, 'UTC+02:00', TRUE),
    ('Europe/Bratislava', 'Europe/Bratislava (UTC+02:00)', 'Europe', 120, 'UTC+02:00', TRUE),
    ('Europe/Brussels', 'Europe/Brussels (UTC+02:00)', 'Europe', 120, 'UTC+02:00', TRUE),
    ('Europe/Budapest', 'Europe/Budapest (UTC+02:00)', 'Europe', 120, 'UTC+02:00', TRUE),
    ('Europe/Busingen', 'Europe/Busingen (UTC+02:00)', 'Europe', 120, 'UTC+02:00', TRUE),
    ('Europe/Copenhagen', 'Europe/Copenhagen (UTC+02:00)', 'Europe', 120, 'UTC+02:00', TRUE),
    ('Europe/Gibraltar', 'Europe/Gibraltar (UTC+02:00)', 'Europe', 120, 'UTC+02:00', TRUE),
    ('Europe/Kaliningrad', 'Europe/Kaliningrad (UTC+02:00)', 'Europe', 120, 'UTC+02:00', TRUE),
    ('Europe/Ljubljana', 'Europe/Ljubljana (UTC+02:00)', 'Europe', 120, 'UTC+02:00', TRUE),
    ('Europe/Luxembourg', 'Europe/Luxembourg (UTC+02:00)', 'Europe', 120, 'UTC+02:00', TRUE),
    ('Europe/Madrid', 'Europe/Madrid (UTC+02:00)', 'Europe', 120, 'UTC+02:00', TRUE),
    ('Europe/Malta', 'Europe/Malta (UTC+02:00)', 'Europe', 120, 'UTC+02:00', TRUE),
    ('Europe/Monaco', 'Europe/Monaco (UTC+02:00)', 'Europe', 120, 'UTC+02:00', TRUE),
    ('Europe/Oslo', 'Europe/Oslo (UTC+02:00)', 'Europe', 120, 'UTC+02:00', TRUE),
    ('Europe/Paris', 'Europe/Paris (UTC+02:00)', 'Europe', 120, 'UTC+02:00', TRUE),
    ('Europe/Podgorica', 'Europe/Podgorica (UTC+02:00)', 'Europe', 120, 'UTC+02:00', TRUE),
    ('Europe/Prague', 'Europe/Prague (UTC+02:00)', 'Europe', 120, 'UTC+02:00', TRUE),
    ('Europe/Rome', 'Europe/Rome (UTC+02:00)', 'Europe', 120, 'UTC+02:00', TRUE),
    ('Europe/San_Marino', 'Europe/San Marino (UTC+02:00)', 'Europe', 120, 'UTC+02:00', TRUE),
    ('Europe/Sarajevo', 'Europe/Sarajevo (UTC+02:00)', 'Europe', 120, 'UTC+02:00', TRUE),
    ('Europe/Skopje', 'Europe/Skopje (UTC+02:00)', 'Europe', 120, 'UTC+02:00', TRUE),
    ('Europe/Stockholm', 'Europe/Stockholm (UTC+02:00)', 'Europe', 120, 'UTC+02:00', TRUE),
    ('Europe/Tirane', 'Europe/Tirane (UTC+02:00)', 'Europe', 120, 'UTC+02:00', TRUE),
    ('Europe/Vaduz', 'Europe/Vaduz (UTC+02:00)', 'Europe', 120, 'UTC+02:00', TRUE),
    ('Europe/Vatican', 'Europe/Vatican (UTC+02:00)', 'Europe', 120, 'UTC+02:00', TRUE),
    ('Europe/Vienna', 'Europe/Vienna (UTC+02:00)', 'Europe', 120, 'UTC+02:00', TRUE),
    ('Europe/Warsaw', 'Europe/Warsaw (UTC+02:00)', 'Europe', 120, 'UTC+02:00', TRUE),
    ('Europe/Zagreb', 'Europe/Zagreb (UTC+02:00)', 'Europe', 120, 'UTC+02:00', TRUE),
    ('Europe/Zurich', 'Europe/Zurich (UTC+02:00)', 'Europe', 120, 'UTC+02:00', TRUE),
    ('Europe/Athens', 'Europe/Athens (UTC+03:00)', 'Europe', 180, 'UTC+03:00', TRUE),
    ('Europe/Bucharest', 'Europe/Bucharest (UTC+03:00)', 'Europe', 180, 'UTC+03:00', TRUE),
    ('Europe/Chisinau', 'Europe/Chisinau (UTC+03:00)', 'Europe', 180, 'UTC+03:00', TRUE),
    ('Europe/Helsinki', 'Europe/Helsinki (UTC+03:00)', 'Europe', 180, 'UTC+03:00', TRUE),
    ('Europe/Istanbul', 'Europe/Istanbul (UTC+03:00)', 'Europe', 180, 'UTC+03:00', TRUE),
    ('Europe/Kiev', 'Europe/Kiev (UTC+03:00)', 'Europe', 180, 'UTC+03:00', TRUE),
    ('Europe/Kirov', 'Europe/Kirov (UTC+03:00)', 'Europe', 180, 'UTC+03:00', TRUE),
    ('Europe/Mariehamn', 'Europe/Mariehamn (UTC+03:00)', 'Europe', 180, 'UTC+03:00', TRUE),
    ('Europe/Minsk', 'Europe/Minsk (UTC+03:00)', 'Europe', 180, 'UTC+03:00', TRUE),
    ('Europe/Moscow', 'Europe/Moscow (UTC+03:00)', 'Europe', 180, 'UTC+03:00', TRUE),
    ('Europe/Riga', 'Europe/Riga (UTC+03:00)', 'Europe', 180, 'UTC+03:00', TRUE),
    ('Europe/Simferopol', 'Europe/Simferopol (UTC+03:00)', 'Europe', 180, 'UTC+03:00', TRUE),
    ('Europe/Sofia', 'Europe/Sofia (UTC+03:00)', 'Europe', 180, 'UTC+03:00', TRUE),
    ('Europe/Tallinn', 'Europe/Tallinn (UTC+03:00)', 'Europe', 180, 'UTC+03:00', TRUE),
    ('Europe/Vilnius', 'Europe/Vilnius (UTC+03:00)', 'Europe', 180, 'UTC+03:00', TRUE),
    ('Europe/Volgograd', 'Europe/Volgograd (UTC+03:00)', 'Europe', 180, 'UTC+03:00', TRUE),
    ('Europe/Astrakhan', 'Europe/Astrakhan (UTC+04:00)', 'Europe', 240, 'UTC+04:00', TRUE),
    ('Europe/Samara', 'Europe/Samara (UTC+04:00)', 'Europe', 240, 'UTC+04:00', TRUE),
    ('Europe/Saratov', 'Europe/Saratov (UTC+04:00)', 'Europe', 240, 'UTC+04:00', TRUE),
    ('Europe/Ulyanovsk', 'Europe/Ulyanovsk (UTC+04:00)', 'Europe', 240, 'UTC+04:00', TRUE),
    ('Indian/Antananarivo', 'Indian/Antananarivo (UTC+03:00)', 'Indian', 180, 'UTC+03:00', TRUE),
    ('Indian/Comoro', 'Indian/Comoro (UTC+03:00)', 'Indian', 180, 'UTC+03:00', TRUE),
    ('Indian/Mayotte', 'Indian/Mayotte (UTC+03:00)', 'Indian', 180, 'UTC+03:00', TRUE),
    ('Indian/Mahe', 'Indian/Mahe (UTC+04:00)', 'Indian', 240, 'UTC+04:00', TRUE),
    ('Indian/Mauritius', 'Indian/Mauritius (UTC+04:00)', 'Indian', 240, 'UTC+04:00', TRUE),
    ('Indian/Reunion', 'Indian/Reunion (UTC+04:00)', 'Indian', 240, 'UTC+04:00', TRUE),
    ('Indian/Kerguelen', 'Indian/Kerguelen (UTC+05:00)', 'Indian', 300, 'UTC+05:00', TRUE),
    ('Indian/Maldives', 'Indian/Maldives (UTC+05:00)', 'Indian', 300, 'UTC+05:00', TRUE),
    ('Indian/Chagos', 'Indian/Chagos (UTC+06:00)', 'Indian', 360, 'UTC+06:00', TRUE),
    ('Indian/Cocos', 'Indian/Cocos (UTC+06:30)', 'Indian', 390, 'UTC+06:30', TRUE),
    ('Indian/Christmas', 'Indian/Christmas (UTC+07:00)', 'Indian', 420, 'UTC+07:00', TRUE),
    ('Pacific/Midway', 'Pacific/Midway (UTC-11:00)', 'Pacific', -660, 'UTC-11:00', TRUE),
    ('Pacific/Niue', 'Pacific/Niue (UTC-11:00)', 'Pacific', -660, 'UTC-11:00', TRUE),
    ('Pacific/Pago_Pago', 'Pacific/Pago Pago (UTC-11:00)', 'Pacific', -660, 'UTC-11:00', TRUE),
    ('Pacific/Honolulu', 'Pacific/Honolulu (UTC-10:00)', 'Pacific', -600, 'UTC-10:00', TRUE),
    ('Pacific/Rarotonga', 'Pacific/Rarotonga (UTC-10:00)', 'Pacific', -600, 'UTC-10:00', TRUE),
    ('Pacific/Tahiti', 'Pacific/Tahiti (UTC-10:00)', 'Pacific', -600, 'UTC-10:00', TRUE),
    ('Pacific/Marquesas', 'Pacific/Marquesas (UTC-09:30)', 'Pacific', -570, 'UTC-09:30', TRUE),
    ('Pacific/Gambier', 'Pacific/Gambier (UTC-09:00)', 'Pacific', -540, 'UTC-09:00', TRUE),
    ('Pacific/Pitcairn', 'Pacific/Pitcairn (UTC-08:00)', 'Pacific', -480, 'UTC-08:00', TRUE),
    ('Pacific/Easter', 'Pacific/Easter (UTC-06:00)', 'Pacific', -360, 'UTC-06:00', TRUE),
    ('Pacific/Galapagos', 'Pacific/Galapagos (UTC-06:00)', 'Pacific', -360, 'UTC-06:00', TRUE),
    ('Pacific/Palau', 'Pacific/Palau (UTC+09:00)', 'Pacific', 540, 'UTC+09:00', TRUE),
    ('Pacific/Guam', 'Pacific/Guam (UTC+10:00)', 'Pacific', 600, 'UTC+10:00', TRUE),
    ('Pacific/Port_Moresby', 'Pacific/Port Moresby (UTC+10:00)', 'Pacific', 600, 'UTC+10:00', TRUE),
    ('Pacific/Saipan', 'Pacific/Saipan (UTC+10:00)', 'Pacific', 600, 'UTC+10:00', TRUE),
    ('Pacific/Truk', 'Pacific/Truk (UTC+10:00)', 'Pacific', 600, 'UTC+10:00', TRUE),
    ('Pacific/Bougainville', 'Pacific/Bougainville (UTC+11:00)', 'Pacific', 660, 'UTC+11:00', TRUE),
    ('Pacific/Efate', 'Pacific/Efate (UTC+11:00)', 'Pacific', 660, 'UTC+11:00', TRUE),
    ('Pacific/Guadalcanal', 'Pacific/Guadalcanal (UTC+11:00)', 'Pacific', 660, 'UTC+11:00', TRUE),
    ('Pacific/Kosrae', 'Pacific/Kosrae (UTC+11:00)', 'Pacific', 660, 'UTC+11:00', TRUE),
    ('Pacific/Norfolk', 'Pacific/Norfolk (UTC+11:00)', 'Pacific', 660, 'UTC+11:00', TRUE),
    ('Pacific/Noumea', 'Pacific/Noumea (UTC+11:00)', 'Pacific', 660, 'UTC+11:00', TRUE),
    ('Pacific/Ponape', 'Pacific/Ponape (UTC+11:00)', 'Pacific', 660, 'UTC+11:00', TRUE),
    ('Pacific/Auckland', 'Pacific/Auckland (UTC+12:00)', 'Pacific', 720, 'UTC+12:00', TRUE),
    ('Pacific/Fiji', 'Pacific/Fiji (UTC+12:00)', 'Pacific', 720, 'UTC+12:00', TRUE),
    ('Pacific/Funafuti', 'Pacific/Funafuti (UTC+12:00)', 'Pacific', 720, 'UTC+12:00', TRUE),
    ('Pacific/Kwajalein', 'Pacific/Kwajalein (UTC+12:00)', 'Pacific', 720, 'UTC+12:00', TRUE),
    ('Pacific/Majuro', 'Pacific/Majuro (UTC+12:00)', 'Pacific', 720, 'UTC+12:00', TRUE),
    ('Pacific/Nauru', 'Pacific/Nauru (UTC+12:00)', 'Pacific', 720, 'UTC+12:00', TRUE),
    ('Pacific/Tarawa', 'Pacific/Tarawa (UTC+12:00)', 'Pacific', 720, 'UTC+12:00', TRUE),
    ('Pacific/Wake', 'Pacific/Wake (UTC+12:00)', 'Pacific', 720, 'UTC+12:00', TRUE),
    ('Pacific/Wallis', 'Pacific/Wallis (UTC+12:00)', 'Pacific', 720, 'UTC+12:00', TRUE),
    ('Pacific/Chatham', 'Pacific/Chatham (UTC+12:45)', 'Pacific', 765, 'UTC+12:45', TRUE),
    ('Pacific/Apia', 'Pacific/Apia (UTC+13:00)', 'Pacific', 780, 'UTC+13:00', TRUE),
    ('Pacific/Enderbury', 'Pacific/Enderbury (UTC+13:00)', 'Pacific', 780, 'UTC+13:00', TRUE),
    ('Pacific/Fakaofo', 'Pacific/Fakaofo (UTC+13:00)', 'Pacific', 780, 'UTC+13:00', TRUE),
    ('Pacific/Tongatapu', 'Pacific/Tongatapu (UTC+13:00)', 'Pacific', 780, 'UTC+13:00', TRUE),
    ('Pacific/Kiritimati', 'Pacific/Kiritimati (UTC+14:00)', 'Pacific', 840, 'UTC+14:00', TRUE)
ON CONFLICT (id) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    region = EXCLUDED.region,
    utc_offset_minutes = EXCLUDED.utc_offset_minutes,
    utc_offset = EXCLUDED.utc_offset,
    is_active = EXCLUDED.is_active,
    updated_at = NOW();

INSERT INTO platform.countries (iso_alpha2, name, currency_code, currency_name, currency_symbol, flag_emoji, default_timezone_id, is_active) VALUES
    ('AF', 'Afghanistan', 'AFN', 'Afghan Afghani', 'AFN', '🇦🇫', NULL, TRUE),
    ('AX', 'Åland Islands', 'EUR', 'Euro', '€', '🇦🇽', NULL, TRUE),
    ('AL', 'Albania', 'ALL', 'Albanian Lek', 'ALL', '🇦🇱', NULL, TRUE),
    ('DZ', 'Algeria', 'DZD', 'Algerian Dinar', 'DZD', '🇩🇿', NULL, TRUE),
    ('AS', 'American Samoa', 'USD', 'US Dollar', '$', '🇦🇸', NULL, TRUE),
    ('AD', 'Andorra', 'EUR', 'Euro', '€', '🇦🇩', NULL, TRUE),
    ('AO', 'Angola', 'AOA', 'Angolan Kwanza', 'AOA', '🇦🇴', NULL, TRUE),
    ('AI', 'Anguilla', 'XCD', 'East Caribbean Dollar', 'EC$', '🇦🇮', NULL, TRUE),
    ('AG', 'Antigua & Barbuda', 'XCD', 'East Caribbean Dollar', 'EC$', '🇦🇬', NULL, TRUE),
    ('AR', 'Argentina', 'ARS', 'Argentine Peso', 'ARS', '🇦🇷', NULL, TRUE),
    ('AM', 'Armenia', 'AMD', 'Armenian Dram', 'AMD', '🇦🇲', NULL, TRUE),
    ('AW', 'Aruba', 'AWG', 'Aruban Florin', 'AWG', '🇦🇼', NULL, TRUE),
    ('AC', 'Ascension Island', 'SHP', 'St. Helena Pound', 'SHP', '🇦🇨', NULL, TRUE),
    ('AU', 'Australia', 'AUD', 'Australian Dollar', 'A$', '🇦🇺', NULL, TRUE),
    ('AT', 'Austria', 'EUR', 'Euro', '€', '🇦🇹', NULL, TRUE),
    ('AZ', 'Azerbaijan', 'AZN', 'Azerbaijani Manat', 'AZN', '🇦🇿', NULL, TRUE),
    ('BS', 'Bahamas', 'BSD', 'Bahamian Dollar', 'BSD', '🇧🇸', NULL, TRUE),
    ('BH', 'Bahrain', 'BHD', 'Bahraini Dinar', 'BHD', '🇧🇭', NULL, TRUE),
    ('BD', 'Bangladesh', 'BDT', 'Bangladeshi Taka', 'BDT', '🇧🇩', NULL, TRUE),
    ('BB', 'Barbados', 'BBD', 'Barbadian Dollar', 'BBD', '🇧🇧', NULL, TRUE),
    ('BY', 'Belarus', 'BYN', 'Belarusian Ruble', 'BYN', '🇧🇾', NULL, TRUE),
    ('BE', 'Belgium', 'EUR', 'Euro', '€', '🇧🇪', NULL, TRUE),
    ('BZ', 'Belize', 'BZD', 'Belize Dollar', 'BZD', '🇧🇿', NULL, TRUE),
    ('BJ', 'Benin', 'XOF', 'West African CFA Franc', 'F CFA', '🇧🇯', NULL, TRUE),
    ('BM', 'Bermuda', 'BMD', 'Bermudan Dollar', 'BMD', '🇧🇲', NULL, TRUE),
    ('BT', 'Bhutan', 'BTN', 'Bhutanese Ngultrum', 'BTN', '🇧🇹', NULL, TRUE),
    ('BO', 'Bolivia', 'BOB', 'Bolivian Boliviano', 'BOB', '🇧🇴', NULL, TRUE),
    ('BA', 'Bosnia & Herzegovina', 'BAM', 'Bosnia-Herzegovina Convertible Mark', 'BAM', '🇧🇦', NULL, TRUE),
    ('BW', 'Botswana', 'BWP', 'Botswanan Pula', 'BWP', '🇧🇼', NULL, TRUE),
    ('BV', 'Bouvet Island', 'NOK', 'Norwegian Krone', 'NOK', '🇧🇻', NULL, TRUE),
    ('BR', 'Brazil', 'BRL', 'Brazilian Real', 'R$', '🇧🇷', NULL, TRUE),
    ('IO', 'British Indian Ocean Territory', 'USD', 'US Dollar', '$', '🇮🇴', NULL, TRUE),
    ('VG', 'British Virgin Islands', 'USD', 'US Dollar', '$', '🇻🇬', NULL, TRUE),
    ('BN', 'Brunei', 'BND', 'Brunei Dollar', 'BND', '🇧🇳', NULL, TRUE),
    ('BG', 'Bulgaria', 'EUR', 'Euro', '€', '🇧🇬', NULL, TRUE),
    ('BF', 'Burkina Faso', 'XOF', 'West African CFA Franc', 'F CFA', '🇧🇫', NULL, TRUE),
    ('BI', 'Burundi', 'BIF', 'Burundian Franc', 'BIF', '🇧🇮', NULL, TRUE),
    ('KH', 'Cambodia', 'KHR', 'Cambodian Riel', 'KHR', '🇰🇭', NULL, TRUE),
    ('CM', 'Cameroon', 'XAF', 'Central African CFA Franc', 'FCFA', '🇨🇲', NULL, TRUE),
    ('CA', 'Canada', 'CAD', 'Canadian Dollar', 'CA$', '🇨🇦', NULL, TRUE),
    ('IC', 'Canary Islands', 'EUR', 'Euro', '€', '🇮🇨', NULL, TRUE),
    ('CV', 'Cape Verde', 'CVE', 'Cape Verdean Escudo', 'CVE', '🇨🇻', NULL, TRUE),
    ('BQ', 'Caribbean Netherlands', 'USD', 'US Dollar', '$', '🇧🇶', NULL, TRUE),
    ('KY', 'Cayman Islands', 'KYD', 'Cayman Islands Dollar', 'KYD', '🇰🇾', NULL, TRUE),
    ('CF', 'Central African Republic', 'XAF', 'Central African CFA Franc', 'FCFA', '🇨🇫', NULL, TRUE),
    ('EA', 'Ceuta & Melilla', 'EUR', 'Euro', '€', '🇪🇦', NULL, TRUE),
    ('TD', 'Chad', 'XAF', 'Central African CFA Franc', 'FCFA', '🇹🇩', NULL, TRUE),
    ('CL', 'Chile', 'CLP', 'Chilean Peso', 'CLP', '🇨🇱', NULL, TRUE),
    ('CN', 'China', 'CNY', 'Chinese Yuan', 'CN¥', '🇨🇳', NULL, TRUE),
    ('CX', 'Christmas Island', 'AUD', 'Australian Dollar', 'A$', '🇨🇽', NULL, TRUE),
    ('CC', 'Cocos (Keeling) Islands', 'AUD', 'Australian Dollar', 'A$', '🇨🇨', NULL, TRUE),
    ('CO', 'Colombia', 'COP', 'Colombian Peso', 'COP', '🇨🇴', NULL, TRUE),
    ('KM', 'Comoros', 'KMF', 'Comorian Franc', 'KMF', '🇰🇲', NULL, TRUE),
    ('CG', 'Congo - Brazzaville', 'XAF', 'Central African CFA Franc', 'FCFA', '🇨🇬', NULL, TRUE),
    ('CD', 'Congo - Kinshasa', 'CDF', 'Congolese Franc', 'CDF', '🇨🇩', NULL, TRUE),
    ('CK', 'Cook Islands', 'NZD', 'New Zealand Dollar', 'NZ$', '🇨🇰', NULL, TRUE),
    ('CR', 'Costa Rica', 'CRC', 'Costa Rican Colón', 'CRC', '🇨🇷', NULL, TRUE),
    ('CI', 'Côte d’Ivoire', 'XOF', 'West African CFA Franc', 'F CFA', '🇨🇮', NULL, TRUE),
    ('HR', 'Croatia', 'EUR', 'Euro', '€', '🇭🇷', NULL, TRUE),
    ('CU', 'Cuba', 'CUP', 'Cuban Peso', 'CUP', '🇨🇺', NULL, TRUE),
    ('CW', 'Curaçao', 'XCG', 'Caribbean guilder', 'Cg.', '🇨🇼', NULL, TRUE),
    ('CY', 'Cyprus', 'EUR', 'Euro', '€', '🇨🇾', NULL, TRUE),
    ('CZ', 'Czechia', 'CZK', 'Czech Koruna', 'CZK', '🇨🇿', NULL, TRUE),
    ('DK', 'Denmark', 'DKK', 'Danish Krone', 'DKK', '🇩🇰', NULL, TRUE),
    ('DG', 'Diego Garcia', 'USD', 'US Dollar', '$', '🇩🇬', NULL, TRUE),
    ('DJ', 'Djibouti', 'DJF', 'Djiboutian Franc', 'DJF', '🇩🇯', NULL, TRUE),
    ('DM', 'Dominica', 'XCD', 'East Caribbean Dollar', 'EC$', '🇩🇲', NULL, TRUE),
    ('DO', 'Dominican Republic', 'DOP', 'Dominican Peso', 'DOP', '🇩🇴', NULL, TRUE),
    ('EC', 'Ecuador', 'USD', 'US Dollar', '$', '🇪🇨', NULL, TRUE),
    ('EG', 'Egypt', 'EGP', 'Egyptian Pound', 'EGP', '🇪🇬', NULL, TRUE),
    ('SV', 'El Salvador', 'USD', 'US Dollar', '$', '🇸🇻', NULL, TRUE),
    ('GQ', 'Equatorial Guinea', 'XAF', 'Central African CFA Franc', 'FCFA', '🇬🇶', NULL, TRUE),
    ('ER', 'Eritrea', 'ERN', 'Eritrean Nakfa', 'ERN', '🇪🇷', NULL, TRUE),
    ('EE', 'Estonia', 'EUR', 'Euro', '€', '🇪🇪', NULL, TRUE),
    ('SZ', 'Eswatini', 'SZL', 'Swazi Lilangeni', 'SZL', '🇸🇿', NULL, TRUE),
    ('ET', 'Ethiopia', 'ETB', 'Ethiopian Birr', 'ETB', '🇪🇹', NULL, TRUE),
    ('EU', 'European Union', 'EUR', 'Euro', '€', '🇪🇺', NULL, TRUE),
    ('FK', 'Falkland Islands', 'FKP', 'Falkland Islands Pound', 'FKP', '🇫🇰', NULL, TRUE),
    ('FO', 'Faroe Islands', 'DKK', 'Danish Krone', 'DKK', '🇫🇴', NULL, TRUE),
    ('FJ', 'Fiji', 'FJD', 'Fijian Dollar', 'FJD', '🇫🇯', NULL, TRUE),
    ('FI', 'Finland', 'EUR', 'Euro', '€', '🇫🇮', NULL, TRUE),
    ('FR', 'France', 'EUR', 'Euro', '€', '🇫🇷', NULL, TRUE),
    ('GF', 'French Guiana', 'EUR', 'Euro', '€', '🇬🇫', NULL, TRUE),
    ('PF', 'French Polynesia', 'XPF', 'CFP Franc', 'CFPF', '🇵🇫', NULL, TRUE),
    ('TF', 'French Southern Territories', 'EUR', 'Euro', '€', '🇹🇫', NULL, TRUE),
    ('GA', 'Gabon', 'XAF', 'Central African CFA Franc', 'FCFA', '🇬🇦', NULL, TRUE),
    ('GM', 'Gambia', 'GMD', 'Gambian Dalasi', 'GMD', '🇬🇲', NULL, TRUE),
    ('GE', 'Georgia', 'GEL', 'Georgian Lari', 'GEL', '🇬🇪', NULL, TRUE),
    ('DE', 'Germany', 'EUR', 'Euro', '€', '🇩🇪', NULL, TRUE),
    ('GH', 'Ghana', 'GHS', 'Ghanaian Cedi', 'GHS', '🇬🇭', NULL, TRUE),
    ('GI', 'Gibraltar', 'GIP', 'Gibraltar Pound', 'GIP', '🇬🇮', NULL, TRUE),
    ('GR', 'Greece', 'EUR', 'Euro', '€', '🇬🇷', NULL, TRUE),
    ('GL', 'Greenland', 'DKK', 'Danish Krone', 'DKK', '🇬🇱', NULL, TRUE),
    ('GD', 'Grenada', 'XCD', 'East Caribbean Dollar', 'EC$', '🇬🇩', NULL, TRUE),
    ('GP', 'Guadeloupe', 'EUR', 'Euro', '€', '🇬🇵', NULL, TRUE),
    ('GU', 'Guam', 'USD', 'US Dollar', '$', '🇬🇺', NULL, TRUE),
    ('GT', 'Guatemala', 'GTQ', 'Guatemalan Quetzal', 'GTQ', '🇬🇹', NULL, TRUE),
    ('GG', 'Guernsey', 'GBP', 'British Pound', '£', '🇬🇬', NULL, TRUE),
    ('GN', 'Guinea', 'GNF', 'Guinean Franc', 'GNF', '🇬🇳', NULL, TRUE),
    ('GW', 'Guinea-Bissau', 'XOF', 'West African CFA Franc', 'F CFA', '🇬🇼', NULL, TRUE),
    ('GY', 'Guyana', 'GYD', 'Guyanaese Dollar', 'GYD', '🇬🇾', NULL, TRUE),
    ('HT', 'Haiti', 'HTG', 'Haitian Gourde', 'HTG', '🇭🇹', NULL, TRUE),
    ('HM', 'Heard & McDonald Islands', 'AUD', 'Australian Dollar', 'A$', '🇭🇲', NULL, TRUE),
    ('HN', 'Honduras', 'HNL', 'Honduran Lempira', 'HNL', '🇭🇳', NULL, TRUE),
    ('HK', 'Hong Kong SAR China', 'HKD', 'Hong Kong Dollar', 'HK$', '🇭🇰', NULL, TRUE),
    ('HU', 'Hungary', 'HUF', 'Hungarian Forint', 'HUF', '🇭🇺', NULL, TRUE),
    ('IS', 'Iceland', 'ISK', 'Icelandic Króna', 'ISK', '🇮🇸', NULL, TRUE),
    ('IN', 'India', 'INR', 'Indian Rupee', '₹', '🇮🇳', 'Asia/Kolkata', TRUE),
    ('ID', 'Indonesia', 'IDR', 'Indonesian Rupiah', 'IDR', '🇮🇩', NULL, TRUE),
    ('IR', 'Iran', 'IRR', 'Iranian Rial', 'IRR', '🇮🇷', NULL, TRUE),
    ('IQ', 'Iraq', 'IQD', 'Iraqi Dinar', 'IQD', '🇮🇶', NULL, TRUE),
    ('IE', 'Ireland', 'EUR', 'Euro', '€', '🇮🇪', NULL, TRUE),
    ('IM', 'Isle of Man', 'GBP', 'British Pound', '£', '🇮🇲', NULL, TRUE),
    ('IL', 'Israel', 'ILS', 'Israeli New Shekel', '₪', '🇮🇱', NULL, TRUE),
    ('IT', 'Italy', 'EUR', 'Euro', '€', '🇮🇹', NULL, TRUE),
    ('JM', 'Jamaica', 'JMD', 'Jamaican Dollar', 'JMD', '🇯🇲', NULL, TRUE),
    ('JP', 'Japan', 'JPY', 'Japanese Yen', '¥', '🇯🇵', NULL, TRUE),
    ('JE', 'Jersey', 'GBP', 'British Pound', '£', '🇯🇪', NULL, TRUE),
    ('JO', 'Jordan', 'JOD', 'Jordanian Dinar', 'JOD', '🇯🇴', NULL, TRUE),
    ('KZ', 'Kazakhstan', 'KZT', 'Kazakhstani Tenge', 'KZT', '🇰🇿', NULL, TRUE),
    ('KE', 'Kenya', 'KES', 'Kenyan Shilling', 'KES', '🇰🇪', NULL, TRUE),
    ('KI', 'Kiribati', 'AUD', 'Australian Dollar', 'A$', '🇰🇮', NULL, TRUE),
    ('XK', 'Kosovo', 'EUR', 'Euro', '€', '🇽🇰', NULL, TRUE),
    ('KW', 'Kuwait', 'KWD', 'Kuwaiti Dinar', 'KWD', '🇰🇼', NULL, TRUE),
    ('KG', 'Kyrgyzstan', 'KGS', 'Kyrgyz Som', 'KGS', '🇰🇬', NULL, TRUE),
    ('LA', 'Laos', 'LAK', 'Laotian Kip', 'LAK', '🇱🇦', NULL, TRUE),
    ('LV', 'Latvia', 'EUR', 'Euro', '€', '🇱🇻', NULL, TRUE),
    ('LB', 'Lebanon', 'LBP', 'Lebanese Pound', 'LBP', '🇱🇧', NULL, TRUE),
    ('LS', 'Lesotho', 'ZAR', 'South African Rand', 'ZAR', '🇱🇸', NULL, TRUE),
    ('LR', 'Liberia', 'LRD', 'Liberian Dollar', 'LRD', '🇱🇷', NULL, TRUE),
    ('LY', 'Libya', 'LYD', 'Libyan Dinar', 'LYD', '🇱🇾', NULL, TRUE),
    ('LI', 'Liechtenstein', 'CHF', 'Swiss Franc', 'CHF', '🇱🇮', NULL, TRUE),
    ('LT', 'Lithuania', 'EUR', 'Euro', '€', '🇱🇹', NULL, TRUE),
    ('LU', 'Luxembourg', 'EUR', 'Euro', '€', '🇱🇺', NULL, TRUE),
    ('MO', 'Macao SAR China', 'MOP', 'Macanese Pataca', 'MOP', '🇲🇴', NULL, TRUE),
    ('MG', 'Madagascar', 'MGA', 'Malagasy Ariary', 'MGA', '🇲🇬', NULL, TRUE),
    ('MW', 'Malawi', 'MWK', 'Malawian Kwacha', 'MWK', '🇲🇼', NULL, TRUE),
    ('MY', 'Malaysia', 'MYR', 'Malaysian Ringgit', 'MYR', '🇲🇾', NULL, TRUE),
    ('MV', 'Maldives', 'MVR', 'Maldivian Rufiyaa', 'MVR', '🇲🇻', NULL, TRUE),
    ('ML', 'Mali', 'XOF', 'West African CFA Franc', 'F CFA', '🇲🇱', NULL, TRUE),
    ('MT', 'Malta', 'EUR', 'Euro', '€', '🇲🇹', NULL, TRUE),
    ('MH', 'Marshall Islands', 'USD', 'US Dollar', '$', '🇲🇭', NULL, TRUE),
    ('MQ', 'Martinique', 'EUR', 'Euro', '€', '🇲🇶', NULL, TRUE),
    ('MR', 'Mauritania', 'MRU', 'Mauritanian Ouguiya', 'MRU', '🇲🇷', NULL, TRUE),
    ('MU', 'Mauritius', 'MUR', 'Mauritian Rupee', 'MUR', '🇲🇺', NULL, TRUE),
    ('YT', 'Mayotte', 'EUR', 'Euro', '€', '🇾🇹', NULL, TRUE),
    ('MX', 'Mexico', 'MXN', 'Mexican Peso', 'MX$', '🇲🇽', NULL, TRUE),
    ('FM', 'Micronesia', 'USD', 'US Dollar', '$', '🇫🇲', NULL, TRUE),
    ('MD', 'Moldova', 'MDL', 'Moldovan Leu', 'MDL', '🇲🇩', NULL, TRUE),
    ('MC', 'Monaco', 'EUR', 'Euro', '€', '🇲🇨', NULL, TRUE),
    ('MN', 'Mongolia', 'MNT', 'Mongolian Tugrik', 'MNT', '🇲🇳', NULL, TRUE),
    ('ME', 'Montenegro', 'EUR', 'Euro', '€', '🇲🇪', NULL, TRUE),
    ('MS', 'Montserrat', 'XCD', 'East Caribbean Dollar', 'EC$', '🇲🇸', NULL, TRUE),
    ('MA', 'Morocco', 'MAD', 'Moroccan Dirham', 'MAD', '🇲🇦', NULL, TRUE),
    ('MZ', 'Mozambique', 'MZN', 'Mozambican Metical', 'MZN', '🇲🇿', NULL, TRUE),
    ('MM', 'Myanmar (Burma)', 'MMK', 'Myanmar Kyat', 'MMK', '🇲🇲', NULL, TRUE),
    ('NA', 'Namibia', 'NAD', 'Namibian Dollar', 'NAD', '🇳🇦', NULL, TRUE),
    ('NR', 'Nauru', 'AUD', 'Australian Dollar', 'A$', '🇳🇷', NULL, TRUE),
    ('NP', 'Nepal', 'NPR', 'Nepalese Rupee', 'NPR', '🇳🇵', NULL, TRUE),
    ('NL', 'Netherlands', 'EUR', 'Euro', '€', '🇳🇱', NULL, TRUE),
    ('NC', 'New Caledonia', 'XPF', 'CFP Franc', 'CFPF', '🇳🇨', NULL, TRUE),
    ('NZ', 'New Zealand', 'NZD', 'New Zealand Dollar', 'NZ$', '🇳🇿', NULL, TRUE),
    ('NI', 'Nicaragua', 'NIO', 'Nicaraguan Córdoba', 'NIO', '🇳🇮', NULL, TRUE),
    ('NE', 'Niger', 'XOF', 'West African CFA Franc', 'F CFA', '🇳🇪', NULL, TRUE),
    ('NG', 'Nigeria', 'NGN', 'Nigerian Naira', 'NGN', '🇳🇬', NULL, TRUE),
    ('NU', 'Niue', 'NZD', 'New Zealand Dollar', 'NZ$', '🇳🇺', NULL, TRUE),
    ('NF', 'Norfolk Island', 'AUD', 'Australian Dollar', 'A$', '🇳🇫', NULL, TRUE),
    ('KP', 'North Korea', 'KPW', 'North Korean Won', 'KPW', '🇰🇵', NULL, TRUE),
    ('MK', 'North Macedonia', 'MKD', 'Macedonian Denar', 'MKD', '🇲🇰', NULL, TRUE),
    ('MP', 'Northern Mariana Islands', 'USD', 'US Dollar', '$', '🇲🇵', NULL, TRUE),
    ('NO', 'Norway', 'NOK', 'Norwegian Krone', 'NOK', '🇳🇴', NULL, TRUE),
    ('OM', 'Oman', 'OMR', 'Omani Rial', 'OMR', '🇴🇲', NULL, TRUE),
    ('PK', 'Pakistan', 'PKR', 'Pakistani Rupee', 'PKR', '🇵🇰', NULL, TRUE),
    ('PW', 'Palau', 'USD', 'US Dollar', '$', '🇵🇼', NULL, TRUE),
    ('PS', 'Palestinian Territories', 'ILS', 'Israeli New Shekel', '₪', '🇵🇸', NULL, TRUE),
    ('PA', 'Panama', 'PAB', 'Panamanian Balboa', 'PAB', '🇵🇦', NULL, TRUE),
    ('PG', 'Papua New Guinea', 'PGK', 'Papua New Guinean Kina', 'PGK', '🇵🇬', NULL, TRUE),
    ('PY', 'Paraguay', 'PYG', 'Paraguayan Guarani', 'PYG', '🇵🇾', NULL, TRUE),
    ('PE', 'Peru', 'PEN', 'Peruvian Sol', 'PEN', '🇵🇪', NULL, TRUE),
    ('PH', 'Philippines', 'PHP', 'Philippine Peso', '₱', '🇵🇭', NULL, TRUE),
    ('PN', 'Pitcairn Islands', 'NZD', 'New Zealand Dollar', 'NZ$', '🇵🇳', NULL, TRUE),
    ('PL', 'Poland', 'PLN', 'Polish Zloty', 'PLN', '🇵🇱', NULL, TRUE),
    ('PT', 'Portugal', 'EUR', 'Euro', '€', '🇵🇹', NULL, TRUE),
    ('PR', 'Puerto Rico', 'USD', 'US Dollar', '$', '🇵🇷', NULL, TRUE),
    ('QA', 'Qatar', 'QAR', 'Qatari Riyal', 'QAR', '🇶🇦', NULL, TRUE),
    ('RE', 'Réunion', 'EUR', 'Euro', '€', '🇷🇪', NULL, TRUE),
    ('RO', 'Romania', 'RON', 'Romanian Leu', 'RON', '🇷🇴', NULL, TRUE),
    ('RU', 'Russia', 'RUB', 'Russian Ruble', 'RUB', '🇷🇺', NULL, TRUE),
    ('RW', 'Rwanda', 'RWF', 'Rwandan Franc', 'RWF', '🇷🇼', NULL, TRUE),
    ('WS', 'Samoa', 'WST', 'Samoan Tala', 'WST', '🇼🇸', NULL, TRUE),
    ('SM', 'San Marino', 'EUR', 'Euro', '€', '🇸🇲', NULL, TRUE),
    ('ST', 'São Tomé & Príncipe', 'STN', 'São Tomé & Príncipe Dobra', 'STN', '🇸🇹', NULL, TRUE),
    ('SA', 'Saudi Arabia', 'SAR', 'Saudi Riyal', 'SAR', '🇸🇦', NULL, TRUE),
    ('SN', 'Senegal', 'XOF', 'West African CFA Franc', 'F CFA', '🇸🇳', NULL, TRUE),
    ('RS', 'Serbia', 'RSD', 'Serbian Dinar', 'RSD', '🇷🇸', NULL, TRUE),
    ('SC', 'Seychelles', 'SCR', 'Seychellois Rupee', 'SCR', '🇸🇨', NULL, TRUE),
    ('SL', 'Sierra Leone', 'SLE', 'Sierra Leonean Leone', 'SLE', '🇸🇱', NULL, TRUE),
    ('SG', 'Singapore', 'SGD', 'Singapore Dollar', 'SGD', '🇸🇬', NULL, TRUE),
    ('SX', 'Sint Maarten', 'XCG', 'Caribbean guilder', 'Cg.', '🇸🇽', NULL, TRUE),
    ('SK', 'Slovakia', 'EUR', 'Euro', '€', '🇸🇰', NULL, TRUE),
    ('SI', 'Slovenia', 'EUR', 'Euro', '€', '🇸🇮', NULL, TRUE),
    ('SB', 'Solomon Islands', 'SBD', 'Solomon Islands Dollar', 'SBD', '🇸🇧', NULL, TRUE),
    ('SO', 'Somalia', 'SOS', 'Somali Shilling', 'SOS', '🇸🇴', NULL, TRUE),
    ('ZA', 'South Africa', 'ZAR', 'South African Rand', 'ZAR', '🇿🇦', NULL, TRUE),
    ('GS', 'South Georgia & South Sandwich Islands', 'GBP', 'British Pound', '£', '🇬🇸', NULL, TRUE),
    ('KR', 'South Korea', 'KRW', 'South Korean Won', '₩', '🇰🇷', NULL, TRUE),
    ('SS', 'South Sudan', 'SSP', 'South Sudanese Pound', 'SSP', '🇸🇸', NULL, TRUE),
    ('ES', 'Spain', 'EUR', 'Euro', '€', '🇪🇸', NULL, TRUE),
    ('LK', 'Sri Lanka', 'LKR', 'Sri Lankan Rupee', 'LKR', '🇱🇰', NULL, TRUE),
    ('BL', 'St. Barthélemy', 'EUR', 'Euro', '€', '🇧🇱', NULL, TRUE),
    ('SH', 'St. Helena', 'SHP', 'St. Helena Pound', 'SHP', '🇸🇭', NULL, TRUE),
    ('KN', 'St. Kitts & Nevis', 'XCD', 'East Caribbean Dollar', 'EC$', '🇰🇳', NULL, TRUE),
    ('LC', 'St. Lucia', 'XCD', 'East Caribbean Dollar', 'EC$', '🇱🇨', NULL, TRUE),
    ('MF', 'St. Martin', 'EUR', 'Euro', '€', '🇲🇫', NULL, TRUE),
    ('PM', 'St. Pierre & Miquelon', 'EUR', 'Euro', '€', '🇵🇲', NULL, TRUE),
    ('VC', 'St. Vincent & Grenadines', 'XCD', 'East Caribbean Dollar', 'EC$', '🇻🇨', NULL, TRUE),
    ('SD', 'Sudan', 'SDG', 'Sudanese Pound', 'SDG', '🇸🇩', NULL, TRUE),
    ('SR', 'Suriname', 'SRD', 'Surinamese Dollar', 'SRD', '🇸🇷', NULL, TRUE),
    ('SJ', 'Svalbard & Jan Mayen', 'NOK', 'Norwegian Krone', 'NOK', '🇸🇯', NULL, TRUE),
    ('SE', 'Sweden', 'SEK', 'Swedish Krona', 'SEK', '🇸🇪', NULL, TRUE),
    ('CH', 'Switzerland', 'CHF', 'Swiss Franc', 'CHF', '🇨🇭', NULL, TRUE),
    ('SY', 'Syria', 'SYP', 'Syrian Pound', 'SYP', '🇸🇾', NULL, TRUE),
    ('TW', 'Taiwan', 'TWD', 'New Taiwan Dollar', 'NT$', '🇹🇼', NULL, TRUE),
    ('TJ', 'Tajikistan', 'TJS', 'Tajikistani Somoni', 'TJS', '🇹🇯', NULL, TRUE),
    ('TZ', 'Tanzania', 'TZS', 'Tanzanian Shilling', 'TZS', '🇹🇿', NULL, TRUE),
    ('TH', 'Thailand', 'THB', 'Thai Baht', 'THB', '🇹🇭', NULL, TRUE),
    ('TL', 'Timor-Leste', 'USD', 'US Dollar', '$', '🇹🇱', NULL, TRUE),
    ('TG', 'Togo', 'XOF', 'West African CFA Franc', 'F CFA', '🇹🇬', NULL, TRUE),
    ('TK', 'Tokelau', 'NZD', 'New Zealand Dollar', 'NZ$', '🇹🇰', NULL, TRUE),
    ('TO', 'Tonga', 'TOP', 'Tongan Paʻanga', 'TOP', '🇹🇴', NULL, TRUE),
    ('TT', 'Trinidad & Tobago', 'TTD', 'Trinidad & Tobago Dollar', 'TTD', '🇹🇹', NULL, TRUE),
    ('TA', 'Tristan da Cunha', 'GBP', 'British Pound', '£', '🇹🇦', NULL, TRUE),
    ('TN', 'Tunisia', 'TND', 'Tunisian Dinar', 'TND', '🇹🇳', NULL, TRUE),
    ('TR', 'Türkiye', 'TRY', 'Turkish Lira', 'TRY', '🇹🇷', NULL, TRUE),
    ('TM', 'Turkmenistan', 'TMT', 'Turkmenistani Manat', 'TMT', '🇹🇲', NULL, TRUE),
    ('TC', 'Turks & Caicos Islands', 'USD', 'US Dollar', '$', '🇹🇨', NULL, TRUE),
    ('TV', 'Tuvalu', 'AUD', 'Australian Dollar', 'A$', '🇹🇻', NULL, TRUE),
    ('UM', 'U.S. Outlying Islands', 'USD', 'US Dollar', '$', '🇺🇲', NULL, TRUE),
    ('VI', 'U.S. Virgin Islands', 'USD', 'US Dollar', '$', '🇻🇮', NULL, TRUE),
    ('UG', 'Uganda', 'UGX', 'Ugandan Shilling', 'UGX', '🇺🇬', NULL, TRUE),
    ('UA', 'Ukraine', 'UAH', 'Ukrainian Hryvnia', 'UAH', '🇺🇦', NULL, TRUE),
    ('AE', 'United Arab Emirates', 'AED', 'United Arab Emirates Dirham', 'AED', '🇦🇪', NULL, TRUE),
    ('GB', 'United Kingdom', 'GBP', 'British Pound', '£', '🇬🇧', NULL, TRUE),
    ('US', 'United States', 'USD', 'US Dollar', '$', '🇺🇸', NULL, TRUE),
    ('UY', 'Uruguay', 'UYU', 'Uruguayan Peso', 'UYU', '🇺🇾', NULL, TRUE),
    ('UZ', 'Uzbekistan', 'UZS', 'Uzbekistani Som', 'UZS', '🇺🇿', NULL, TRUE),
    ('VU', 'Vanuatu', 'VUV', 'Vanuatu Vatu', 'VUV', '🇻🇺', NULL, TRUE),
    ('VA', 'Vatican City', 'EUR', 'Euro', '€', '🇻🇦', NULL, TRUE),
    ('VE', 'Venezuela', 'VES', 'Venezuelan Bolívar', 'VES', '🇻🇪', NULL, TRUE),
    ('VN', 'Vietnam', 'VND', 'Vietnamese Dong', '₫', '🇻🇳', NULL, TRUE),
    ('WF', 'Wallis & Futuna', 'XPF', 'CFP Franc', 'CFPF', '🇼🇫', NULL, TRUE),
    ('EH', 'Western Sahara', 'MAD', 'Moroccan Dirham', 'MAD', '🇪🇭', NULL, TRUE),
    ('YE', 'Yemen', 'YER', 'Yemeni Rial', 'YER', '🇾🇪', NULL, TRUE),
    ('ZM', 'Zambia', 'ZMW', 'Zambian Kwacha', 'ZMW', '🇿🇲', NULL, TRUE),
    ('ZW', 'Zimbabwe', 'ZWG', 'Zimbabwean Gold', 'ZWG', '🇿🇼', NULL, TRUE)
ON CONFLICT (iso_alpha2) DO UPDATE SET
    name = EXCLUDED.name,
    currency_code = EXCLUDED.currency_code,
    currency_name = EXCLUDED.currency_name,
    currency_symbol = EXCLUDED.currency_symbol,
    flag_emoji = EXCLUDED.flag_emoji,
    default_timezone_id = EXCLUDED.default_timezone_id,
    is_active = EXCLUDED.is_active,
    updated_at = NOW();
